In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
#preprocess the data
# drop the irreleavant features
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)#col wise
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [5]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [6]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [7]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']) )

geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [9]:
# combine one hot encoded coumns with the original data

data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [10]:
# save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:#write byte mode
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [11]:
# divide the dataset into independent and dependent features
X=data.drop('Exited',axis=1)
y=data['Exited']

#split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
##scale these fetures
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)# imp: do not fit to test data because the model learns from test data which  should not happen, it transforms based on the training params

In [12]:
with open('scaler.pkl','wb') as file:#write byte mode
    pickle.dump(scaler,file)

In [13]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

# ANN Implementation

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

WARNING:tensorflow:From c:\Users\Nikhilesh\Desktop\VSCode\deep-learning-project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [15]:
X_train.shape

(8000, 12)

In [16]:
(X_train.shape[1],)# tuple

(12,)

In [17]:
## Build our ANN model
model=Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),## HL 1 connected with input layer # only specify ",input_shape=(X_train.shape[1],)" for first hidden layer
        Dense(32,activation='relu'), # HL 2
        Dense(1,activation='sigmoid')# output layer
    ]
)

WARNING:tensorflow:From c:\Users\Nikhilesh\Desktop\VSCode\deep-learning-project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [19]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()# we can put this loss param in model.compile or we can also directly specify there
loss

In [20]:
## compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [21]:
## Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard


log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M"
"%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [22]:
# Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [23]:
# Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\Nikhilesh\Desktop\VSCode\deep-learning-project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Nikhilesh\Desktop\VSCode\deep-learning-project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 0.3954 - accuracy: 0.8370 - val_loss: 0.3669 - val_accuracy: 0.8500
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3572 - accuracy: 0.8525 - val_loss: 0.3550 - val_accuracy: 0.8545
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3478 - accuracy: 0.8579 - val_loss: 0.3540 - val_accuracy: 0.8550
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3437 - accuracy: 0.8594 - val_loss: 0.3492 - val_accuracy: 0.8535
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3410 - accuracy: 0.8636 - val_loss: 0.3557 - val_accuracy: 0.8525
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3415 - accuracy: 0.8583 - val_loss: 0.3343 - val_accuracy: 0.8570
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3368 - accuracy: 0.8618 - val_loss: 0.3575 - val_accuracy: 0.8560
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8630 - val_loss: 0.3491 - val_accuracy: 0.8575
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3335 - accuracy: 0.8633 - val_loss: 0.3544 - val_accuracy: 0.8585
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3300 - accuracy: 0.8661 - val_loss: 0.3390 - val_accuracy: 0.8590
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3290 - accuracy: 0.8639 - val_loss: 0.3394 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3254 - accuracy: 0.8627 - val_loss: 0.3601 - val_accuracy: 0.8535
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3230 - accuracy: 0.8668 - val_loss: 0.3360 - val_accuracy: 0.8600
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3181 - accuracy: 0.8681 - val_loss: 0.3642 - val_accuracy: 0.8500
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3198 - accuracy: 0.8690 - val_loss: 0.3593 - val_accuracy: 0.8600
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3157 - accuracy: 0.8680 - val_loss: 0.3411 - val_accuracy: 0.8685

In [24]:
model.save('model.h5')

c:\Users\Nikhilesh\Desktop\VSCode\deep-learning-project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [25]:
## Load Tensorboard Extension

%load_ext tensorboard

In [26]:
%tensorboard --logdir logs/fit --port 6006

In [ ]:
### load the pickle file
##continue in prediction.ipynb